# permissions for end users to view nodescalingwatermarks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodescalingwatermark-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - nodescalingwatermarks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - nodescalingwatermarks/status
  verbs:
  - get
