# permissions for end users to edit nodescalingwatermarks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodescalingwatermark-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - nodescalingwatermarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - nodescalingwatermarks/status
  verbs:
  - get
