apiVersion: redhatcop.redhat.io/v1alpha1
kind: NodeScalingWatermark
metadata:
  name: ai-ml
spec:
  watermarkPercentage: 20
  nodeSelector:
    machine.openshift.io/cluster-api-machine-type: ai-ml
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "ai-ml"
    effect: "NoSchedule"  